import {ObjectId} from 'mongodb'

export interface IResource {
    _id: ObjectId;
    date: Date;
    resourceType: string;
    econType: string;
    title: string;
    desc: string;
    fileLink: string; // link generated by cloudinary
    topics: string[];
}

interface Content {
    _id: ObjectId;
    component: string;
}

interface ContentItem {
    type: string;
    content?: string;
}

export interface IAbout extends Content {
    content: ContentItem[];
}

export interface ICompetition extends Content {
    content: ContentItem[];
}

export interface IResourcesText extends Content {
    content: ContentItem[];
}

