import {ObjectId} from 'mongodb'

export interface IResource {
    _id: ObjectId;
    date: Date;
    resourceType: string;
    econType: string;
    title: string;
    desc: string;
    fileLink: string; // link generated by cloudinary
    topics: string[];
}